###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "fabian@test.com",
    "password" : "123456789"
}

###
POST http://localhost:3000/api/auth/google
Content-Type: application/json

{
    "id_token" : "asdads"
}


###
GET http://localhost:3000/api/category


###
GET http://localhost:3000/api/category/6189eea5ac74fc6d3c349a78

###
POST http://localhost:3000/api/category
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzY0Mjg3MDIsImV4cCI6MTYzNjQzNTkwMn0.prxIqRCb1X9wn561E0wPK-QphGn_ZisXp1mEETXUecs
Content-Type: application/json

{
    "name" : "Kumis"
}

###
PUT http://localhost:3000/api/category/6189eea5ac74fc6d3c349a78
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzY0Mjg3MDIsImV4cCI6MTYzNjQzNTkwMn0.prxIqRCb1X9wn561E0wPK-QphGn_ZisXp1mEETXUecs
Content-Type: application/json

{
    "name" : "galleta"
}

###
DELETE http://localhost:3000/api/category/6189eea5ac74fc6d3c349a78
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzY0Mjg3MDIsImV4cCI6MTYzNjQzNTkwMn0.prxIqRCb1X9wn561E0wPK-QphGn_ZisXp1mEETXUecs
Content-Type: application/json

# Product


###
GET http://localhost:3000/api/product


###
GET http://localhost:3000/api/product/619565dd260a6073f92e687e


###
POST http://localhost:3000/api/product
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzcxODAyNDgsImV4cCI6MTYzNzE4NzQ0OH0.yRbl-s-gKMMZ1PYcSSZrj6vcBUJvwgYaM0Td08B73jU
Content-Type: application/json

{
    "name" : "Producto 3",
    "category" : "6189f04b92ebac41669a252b"    
}

###
PUT http://localhost:3000/api/product/6195661d939506882abf19d4
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzcxODAyNDgsImV4cCI6MTYzNzE4NzQ0OH0.yRbl-s-gKMMZ1PYcSSZrj6vcBUJvwgYaM0Td08B73jU
Content-Type: application/json

{
    "name" : "PRODUCTO 11221"
}


###
DELETE http://localhost:3000/api/product/61956631db94b273da85db6a
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTY1MGVmMDRjYzVkMjI5NGVlNzM0NTUiLCJpYXQiOjE2MzcxODAyNDgsImV4cCI6MTYzNzE4NzQ0OH0.yRbl-s-gKMMZ1PYcSSZrj6vcBUJvwgYaM0Td08B73jU
Content-Type: application/json